---
- name: Setup
  hosts: all
  become: true

  tasks:
    - name: Configure user
      user:
        name: joe

    - name: Add my SSH keys
      authorized_key:
        user: joe
        key: https://github.com/joenyland.keys
        exclusive: true  # Only allow keys specified here

    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade system packages
      apt:
        upgrade: true
        autoremove: true  # Remove old packages
        purge: true  # Purge config files for old packages that were removed

    - name: Install packages
      apt:
        name:
          - htop
          - multitail
          - vim
          - git
          - tree
          - screen
          - gpg
          - ssh

    - name: Set default editor
      alternatives:
        name: editor
        path: /usr/bin/vim.basic

    - name: Allow users in the sudo group to use sudo without providing their password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
