---
- name: Setup
  hosts: all
  become: true

  tasks:
    # TODO: Plex
    # TODO: Disable root SSH
    # TODO: Disable SSH with password

    - name: Configure user
      user:
        name: joe

    - name: Add my SSH keys
      authorized_key:
        user: joe
        key: https://github.com/joenyland.keys
        exclusive: true  # Only allow keys specified here

    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade system packages
      apt:
        upgrade: true
        autoremove: true  # Remove old packages
        purge: true  # Purge config files for old packages that were removed

    - name: Install packages
      apt:
        name:
          - htop
          - multitail
          - vim
          - git
          - tree
          - screen
          - gpg
          - scdaemon
          - ssh
          - rsync
          - bash-completion
          - nfs-client

    - name: Set default editor
      alternatives:
        name: editor
        path: /usr/bin/vim.basic

    - name: Allow users in the sudo group to use sudo without providing their password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Mount server share
      mount:
        path: /srv
        src: server:/srv
        fstype: nfs4
        state: mounted

    - name: Install homeshick
      become: false
      git:
        repo: https://github.com/andsens/homeshick.git
        dest: /home/joe/.homesick/repos/homeshick
        force: yes

- name: Install Brave
  hosts: all
  become: true

  tasks:
    - name: Install packages
      apt:
        name: apt-transport-https
    - name: Install GPG key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/brave.gpg
    - name: Install repo
      apt_repository:
        repo: 'deb https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present
        filename: brave
    - name: Install Brave
      apt:
        name: brave-browser
        update_cache: true
        cache_valid_time: 86400

- name: Install Atom
  hosts: all
  become: true

  tasks:
    - name: Install packages
      apt:
        name: apt-transport-https
    - name: Install GPG key
      apt_key:
        url: https://packagecloud.io/AtomEditor/atom/gpgkey
        state: present
        keyring: /etc/apt/trusted.gpg.d/atom.gpg
    - name: Install repo
      apt_repository:
        repo: 'deb https://packagecloud.io/AtomEditor/atom/any/ any main'
        state: present
        filename: atom
    - name: Install Atom
      apt:
        name: atom
        update_cache: true
        cache_valid_time: 86400
